In [57]:
arr = [1,2,3,4,5,6]
arr[2]

3

### 数组属性：
 ndim  返回int 表示数组维数  
 shape  返回tuple，表示数组尺寸，n行m列的矩阵，形状为(n,m)  
 size  返回int 表示数组元素总数，等于数组形状的乘积  
 dtype 返回data-type，描述数组中元素的类型  
 itemsize 返回int，表示数组每个元素的大小，例如一个float的数组的itemsize属性值时8 

In [1]:
import numpy as np  # 重命名

arr1 = np.array([1,2,3,4,5,6])
print("创建的一维数组时：\n",arr1)

创建的一维数组时：
 [1 2 3 4 5 6]


In [11]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("创建的是二维数组:\n",arr2)
print("数组的尺寸：",arr2.shape)
print("数组类型：",arr2.dtype)
print("数组的每个元素大小:",arr2.itemsize)
print("数组元素个数：",arr2.size)

创建的是二维数组:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
数组的尺寸： (3, 3)
数组类型： int32
数组的每个元素大小: 4
数组元素个数： 9


##### 生成数组

In [12]:
#   初值，终值，步长；从0到1，每隔0.2取一个数
print("使用arange函数创建数组",np.arange(0,1,0.2))   #前包后闭

[0.  0.2 0.4 0.6 0.8]


In [17]:
# 初值，终值，个数；从0到1，一共取6个数
print("使用linspace函数创建数组:",np.linspace(0,1,6))

使用linspace函数创建数组: [0.  0.2 0.4 0.6 0.8 1. ]


In [18]:
print("使用logspace生成等比数列的数组：",np.logspace(0,2,4))

 [  1.           4.64158883  21.5443469  100.        ]


In [29]:
print("使用zeros函数生成元素全是0的数组：\n",np.zeros((3,2)))

使用zeros函数生成元素全是0的数组：
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [30]:
print("使用eye函数生成除了对角线是1，其他元素全是0的数组：\n",np.eye(6))

使用eye函数生成除了对角线是1，其他元素全是0的数组：
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [33]:
print("使用diag生成除了对角线之外元素都是0，且自定义对角线元素的数组：\n",np.diag([1,2,3,5,55,0]))

使用diag生成除了对角线之外元素都是0，且自定义对角线元素的数组：
 [[ 1  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  3  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0 55  0]
 [ 0  0  0  0  0  0]]


In [36]:
print("使用ones函数生成元素全是1的矩阵：\n",np.ones((6,5)))

使用ones函数生成元素全是1的矩阵：
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
print("生成随机数组：",np.random.random(10))

生成随机数组： [0.77723134 0.46213504 0.03000105 0.33233773 0.06496446 0.21175854
 0.96120259 0.71322584 0.41554397 0.02488614]


In [49]:
print("生成均匀分布的随机数组：",np.random.rand(5,4))

[[0.29281508 0.56955467 0.08451923 0.33090024]
 [0.17773833 0.97093179 0.60326163 0.61798647]
 [0.48742822 0.14181394 0.01460754 0.55676853]
 [0.33392022 0.71755797 0.93438433 0.84622066]
 [0.48277788 0.6990389  0.57719059 0.24181558]]


In [54]:
print("使用randint生成有元素有上下限范围的随机数数组：\n",np.random.randint(0,5,size=[5,5],dtype=np.int))  #前包后闭

使用randint生成有元素有上下限范围的随机数数组：
 [[4 4 0 0 4]
 [1 0 2 3 3]
 [3 1 2 3 4]
 [0 0 2 0 2]
 [4 4 1 2 3]]


In [56]:
print("生成高斯分布的数组（钟形曲线）:\n",np.random.randn(4,5))

生成高斯分布的数组（钟形曲线）:
 [[ 0.76822858 -0.34506711 -1.33485582  0.37953398  0.817324  ]
 [-2.05736878  0.21514315 -1.33968691  0.31303367  1.55325663]
 [ 1.1732136  -0.71152485  1.08088006 -0.25201781 -0.69572528]
 [-0.37864317 -1.01873435 -0.1173605   0.23870886 -2.03936668]]


####  存储和读取数据
savetxt()保存  
loadtxt()读取   

In [3]:
txta = np.array([1,2,3,4,5,6])
# np.savetxt('路径',需要保存的内容,格式)
np.savetxt('files/numpy_out.txt',txta,fmt="%d")
txtb = np.loadtxt('files/numpy_out.txt',delimiter=',',dtype=float)
print(txtb)

[1. 2. 3. 4. 5. 6.]


In [12]:
# txtc = np.arange(0,10,0.5).reshape(行,列)
txtc = np.arange(0,10,0.5).reshape(5,-1)  #只改行
print(txtc)
# txtc = np.arange(0,10,0.5).reshape(-1,2)  #只改列
np.savetxt('files/numpy_out2.txt',txtc,fmt="%d",delimiter=",") #逗号分割，保存为整数
txtd = np.loadtxt('files/numpy_out2.txt',delimiter=',')
print(txtd)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]
 [6.  6.5 7.  7.5]
 [8.  8.5 9.  9.5]]
[[0. 0. 1. 1.]
 [2. 2. 3. 3.]
 [4. 4. 5. 5.]
 [6. 6. 7. 7.]
 [8. 8. 9. 9.]]


#### 类型转换

In [43]:
print(np.float64(40))
print(np.int8(384))  #-128~127
print(np.bool(0))
print(np.bool(10))
print(np.float(True))
print(np.float(False))

40.0
-128
False
True
1.0
0.0


#### 索引与切片 

In [51]:
arr = np.arange(8)
print(arr)
print(arr[4])
print(arr[2:5])
print(arr[2:])
print(arr[:5])
print(arr[7])
print(arr[-1])

# 修改切片之后的值
arr[2:4] = 99,100
print(arr)

#每隔一个元素取一个元素
print(arr[1:7:2])

[0 1 2 3 4 5 6 7]
4
[2 3 4]
[2 3 4 5 6 7]
[0 1 2 3 4]
7
7
[  0   1  99 100   4   5   6   7]
[  1 100   5]


二维数组的索引与切片

In [60]:
arr = np.arange(10*10,dtype=int).reshape(10,10)
print("创建的二维数组:\n",arr)
print("------")
print("取2-8的偶数行:\n",arr[2:9:2,:])
print("------")
print("取2-8偶数行中，第6列之后的元素数据：\n",arr[2:9:2,5:])

创建的二维数组:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
------
取2-8的偶数行:
 [[20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]]
------
取2-8偶数行中，第6列之后的元素数据：
 [[25 26 27 28 29]
 [45 46 47 48 49]
 [65 66 67 68 69]
 [85 86 87 88 89]]


In [62]:
print("从后向前，第6列倒序向前一直到第1列：\n",arr[2:9:2,5::-1])

从后向前，第6列倒序向前一直到第1列：
 [[25 24 23 22 21 20]
 [45 44 43 42 41 40]
 [65 64 63 62 61 60]
 [85 84 83 82 81 80]]


按照条件索引

In [67]:
print(arr)
print("-----")
row_index = (arr[:,0]>=50)&(arr[:,0]<=80)
col_index = (arr[0,:]>=5)
print("切片之后的数据：\n",arr[row_index,:][:,col_index])
# 取前四行，前5列数据
print("-----")
row_index = (arr[:,0]<40)
col_index = (arr[0,:]<=4)
print("切片之后的数据：\n",arr[row_index,:][:,col_index])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
-----
切片之后的数据：
 [[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]]
-----
切片之后的数据：
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [8]:
# 花式索引
# 二维数组，用两个整数来定位一个元素(1,0)(1,2)(2,4)(7,8)
row_index = [1,1,2,7]
col_index = [0,2,4,8]
arr[row_index,col_index]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [11]:
import numpy as np
# 索引和切片只是为了查看，并不是为了修改；如果想要修改数据，必须创建一个新的数据，使用copy()，不然数据就会修改到元数据上
arr = np.arange(10*10,dtype=int).reshape(10,10)
newArr = arr[2:9:2,5:].copy()
newArr

array([[25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49],
       [65, 66, 67, 68, 69],
       [85, 86, 87, 88, 89]])

### Numpy的统计分析

####  排序  
1. 直接排序sort() 
2. 间接排序argsort(),lexsort()

#####  直接排序

In [34]:
# sort() 对数值排序
np.random.seed(60)
arr = np.random.randint(1,20,size=10)
print("创建的随机数组：",arr)
arr.sort()
print("排序之后的数据：",arr)

创建的随机数组： [14  2  7 11 16  4  9 18  3  2]
排序之后的数据： [ 2  2  3  4  7  9 11 14 16 18]


In [51]:
np.random.seed(40)
arr = np.random.randint(1,20,size=(5,5))
print("创建的随机数组：\n",arr)
arr.sort(axis=0)  # 按列排序
print("-----")
print(arr)
arr.sort(axis = 1) #按行排序
print("-----")
print(arr)

创建的随机数组：
 [[ 7  8  6 19  2]
 [13  8 19 11 10]
 [ 1 18 10  9 16]
 [15  9 11  4  4]
 [ 8 18 14  6 19]]
-----
[[ 1  8  6  4  2]
 [ 7  8 10  6  4]
 [ 8  9 11  9 10]
 [13 18 14 11 16]
 [15 18 19 19 19]]
-----
[[ 1  2  4  6  8]
 [ 4  6  7  8 10]
 [ 8  9  9 10 11]
 [11 13 14 16 18]
 [15 18 19 19 19]]


#####  间接排序 argsort()
间接排序输出的是排序之后的索引

In [66]:
arr = np.array([0,6,3,9,1])  # 0,1,3,6,9
arr.argsort()
print("元数据：\n",arr)
print("直接排序之后数组：\n  0,1,3,6,9")
print("argsort排序之后的数据：\n",arr.argsort())

元数据：
 [0 6 3 9 1]
直接排序之后数组：
  0,1,3,6,9
argsort排序之后的数据：
 [0 4 2 1 3]


##### 间接排序 lexsort()

In [71]:
# 小升初考试，重点班录取学生按照总成绩录取。在总成绩相同时
# 数学成绩高的优先录取，在总成绩和数学成绩都相同时，按照英语成绩录取……
a_totle = np.array([1,5,1,4,3,4,4])  
# (0,1)  (1,5)  (2,1)  (3,4)  (4,3)  (5,4)  (6,4)
ac = a_totle.copy()
print("总成绩的排序：",ac)
print("总成绩排序索引：",ac.argsort())
b_math = np.array([9,4,0,4,0,2,1])
# (0,9) (2,0) (3,4)  (4,0) (5,2) (6,1) (1,4)
bc =b_math.copy()
print("排序结果是：",np.lexsort((bc,ac)))

总成绩的排序： [1 5 1 4 3 4 4]
总成绩排序索引： [0 2 4 3 5 6 1]
排序结果是： [2 0 4 6 5 3 1]


In [72]:
# 小升初考试，重点班录取学生按照总成绩录取。在总成绩相同时
# 数学成绩高的优先录取，在总成绩和数学成绩都相同时，按照英语成绩录取……
a_totle = np.array([1,5,1,4,3,4,4])  
b_math = np.array([9,4,0,4,0,2,1])
print("排序结果是：",np.lexsort((b_math,a_totle)))

排序结果是： [2 0 4 6 5 3 1]


### 数据清洗

unique函数，查找唯一值并返回已排序结果

In [73]:
arrs = ['train','bus','car','ship','subway','ship','bicycle']
print("去重取唯一：",np.unique(arrs))

去重取唯一： ['bicycle' 'bus' 'car' 'ship' 'subway' 'train']


In [74]:
arrs = [1,1,1,2,3,4,5,7,8,6,5,6,7,8,6,10,1023]
print("去重取唯一的数组：",np.unique(arrs))

去重取唯一的数组： [   1    2    3    4    5    6    7    8   10 1023]


数据的重复操作
1. tile()
2. repeat()  

tile对数组整体进行重复  
repeat对数组元素进行重复

In [77]:
arr = np.arange(5)
print(arr)
print(np.tile(arr,4))

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [89]:
np.random.seed(50)
arr = np.random.randint(1,10,size=(3,3))
print(arr)
print("------")
print(np.repeat(arr,2,axis=1)) #对横轴重复
print("-----")
print(np.repeat(arr,2,axis=0))  #对纵轴重复

[[1 1 2]
 [5 7 6]
 [7 7 6]]
------
[[1 1 1 1 2 2]
 [5 5 7 7 6 6]
 [7 7 7 7 6 6]]
-----
[[1 1 2]
 [1 1 2]
 [5 7 6]
 [5 7 6]
 [7 7 6]
 [7 7 6]]


###  统计函数

#####  求和

In [96]:
arr = np.arange(20).reshape(4,5)
print("创建的数组是：\n",arr)
print("求和:",np.sum(arr))
print("纵轴求和",np.sum(arr,axis=0))
print("横轴求和",np.sum(arr,axis=1))

创建的数组是：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
求和: 190
纵轴求和 [30 34 38 42 46]
求和 [10 35 60 85]


#####  平均值

In [100]:
# mean
print("求均值:",np.mean(arr))
print("求纵轴均值:",np.mean(arr,axis=0))
print("求横轴均值：",np.mean(arr,axis=1))

求均值: 9.5
求纵轴均值: [ 7.5  8.5  9.5 10.5 11.5]
求横轴均值： [ 2.  7. 12. 17.]


##### 求最值

In [101]:
print(np.min(arr)) #最小值
print(np.max(arr)) #最大值

0
19


### 销售价格表统计分析

1. 先输出所有元数据的价格
2. 对数据进行直接排序并输出
3. 去掉重复数据
4. 计算所有价格总和
5. 获取最低价格
6. 获取最高价格

txta = np.array([1,2,3,4,5,6])  
np.savetxt('路径',需要保存的内容,格式)  
np.savetxt('files/numpy_out.txt',txta,fmt="%d")  
txtb = np.loadtxt('files/numpy_out.txt',delimiter=',',dtype=float)  
print(txtb)