ndim 返回int 表示数组维数

shape 返回tuple，表示数组 n行m列的矩阵，形状为（n，m）

size 返回int 表示元素总数，等于数组形状的乘积

dtype 返回

In [1]:
import numpy as np #导包
import pandas
arr1= np.array([1,2,3,4,5,6])
print("创建一维数组:\n",arr1)

创建一维数组:
 [1 2 3 4 5 6]


In [4]:
arr2 =np.array([[123],[456],[789]])
print("创建",arr2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.size)
print(arr2.itemsize)

创建 [[123]
 [456]
 [789]]
(3, 1)
int32
3
4


##### 生成数组

In [27]:
print("使用arange创建数组",np.arange(0,1,0.2))#0-1每隔0.2输出一个数

生成数组 [0.  0.2 0.4 0.6 0.8]


In [25]:
print("使用linspace创建数组",np.linspace(0,1,6))#0-6之间等比生成6个数

使用linspace创建数组 [0.  0.2 0.4 0.6 0.8 1. ]


In [28]:
print("使用logspace生成等比例数组",np.logspace(0,2,4))

使用logspace生成等比例数组 [  1.           4.64158883  21.5443469  100.        ]


In [33]:
print("生成元素全是零的数组",np.zeros((3,2)))

生成元素全是零的数组 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
print("生成除了对角线是1，其他全是零的数组",np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [38]:
print("生成除了对角线其他全是零,且自定义对角线元素的数组",np.diag([1,2,3,4,5,6]))

生成除了对角线其他全是零,且自定义对角线元素的数组 [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [13]:
print("使用ones函数生成全是1的矩阵",np.ones((6,5)))

使用ones函数生成全是1的矩阵 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
print("随机数组",np.random.random((6,5)))

随机数组 [[0.36906636 0.22831832 0.26350494 0.0036593  0.78888314]
 [0.31637563 0.25784912 0.89230934 0.66290642 0.54356129]
 [0.25393015 0.28427    0.47914263 0.05663003 0.78315587]
 [0.41012428 0.97344734 0.3898163  0.28384637 0.72902134]
 [0.90169732 0.49655095 0.59198799 0.79202229 0.78598595]
 [0.88250657 0.29819645 0.77399128 0.31025282 0.69506219]]


In [14]:
print("生成均匀分布的随机数组",np.random.rand(5,4))

生成均匀分布的随机数组 [[0.18884972 0.88900832 0.39429612 0.65896399]
 [0.15545865 0.83275351 0.09349415 0.8512171 ]
 [0.67823598 0.61531646 0.05105781 0.33886085]
 [0.84454771 0.32104201 0.37589658 0.25865447]
 [0.28214273 0.37515876 0.32206467 0.5975196 ]]


In [15]:
print("使用有上下限的随机数组",np.random.randint(0,5,size=[5,5],dtype=int))

使用有上下限的随机数组 [[2 0 2 3 4]
 [4 1 0 0 1]
 [3 0 0 1 4]
 [3 2 2 2 1]
 [0 2 3 4 3]]


In [16]:
print("使用randn生成高斯分布",np.random.randn(4,5))

使用randn生成高斯分布 [[ 1.67827252 -0.38664267  0.20467802 -1.18522159 -0.09345745]
 [ 0.3067038   0.79795233 -0.84815005 -1.00391499 -0.26078639]
 [ 0.32749017  1.28051582  0.61726416 -1.72181211 -0.31879934]
 [ 0.60314036 -0.04924035  1.62692193 -0.20889174 -0.68924322]]


### 存储和读取数据
savetxt()
loadtxt()

In [23]:
txta=np.array([1,2,3,4,5,6])
np.savetxt('numpy_out.txt',txta,fmt="%d")
txtb=np.loadtxt('numpy_out.txt',delimiter=',',dtype=float)
print(txtb)

[1. 2. 3. 4. 5. 6.]


In [51]:
txtc=np.arange(0,10,0.5).reshape(5,-1)
print(textc)
np.savetxt('numpy_out2.txt',txtc,fmt="%d",delimiter=',')
txtb=np.loadtxt('numpy_out2.txta',delimiter=',')
print(txtb)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]
 [6.  6.5 7.  7.5]
 [8.  8.5 9.  9.5]]
[1. 2. 3. 4. 5. 6.]


In [50]:
print(np.int8(1024))#-128~127

0


## 索引和切片

In [55]:
arr=np.arange(8)
print(arr)
print(arr[4])
print(arr[2:5])
print(arr[2:])
print(arr[:5])
print(arr[7])
print(arr[-1])
#修改切片之后的直
arr[2:4]=99,100
print(arr)
#每隔一个元素取一个元素
print(arr[1:7:2])

[0 1 2 3 4 5 6 7]
4
[2 3 4]
[2 3 4 5 6 7]
[0 1 2 3 4]
7
7
[  0   1  99 100   4   5   6   7]
[  1 100   5]


### 二维数组与切片 

In [60]:
arr=np.arange(10*10,dtype=int).reshape(10,10)
print("创建数组:\n",arr)
print('----------------------------')
print("二到八的偶数行",arr[2:9:2,:])
print('-----------------------------')
print('取二刀八偶数行中，第六列之后的元素：\n',arr[2:9:2,5:])

创建数组:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
----------------------------
二到八的偶数行 [[20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]]
-----------------------------
取二刀八偶数行中，第六列之后的元素：
 [[25 26 27 28 29]
 [45 46 47 48 49]
 [65 66 67 68 69]
 [85 86 87 88 89]]


In [63]:
print("从后向前，第六列倒序向前一直到底一列：\n",arr[2:9:2,5::-1])

从后向前，第六列倒序向前一直到底一列：
 [[25 24 23 22 21 20]
 [45 44 43 42 41 40]
 [65 64 63 62 61 60]
 [85 84 83 82 81 80]]


### 按照条件索引


In [74]:
print(arr)
print('-----------------------')
row_index = (arr[:,0]>=50)&(arr[:,0]<=80)
col_index = (arr[0,:]>=5)
print('切片之后的数据：\n',arr[row_index,:][:,col_index])
#取前四行 钱五列
print('-----------------------')
row_index = (arr[:,0]<40)
col_index = (arr[0,:]<=4)
print('切片之后的数据：\n',arr[row_index,:][:,col_index])
#取前四行 钱五列
print()

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
-----------------------
切片之后的数据：
 [[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]]
-----------------------
切片之后的数据：
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]



In [1]:
import numpy as np

arr = np.arange(10 * 10, dtype=int).reshape(10, 10)
newArr = arr[2:9:2, 5:].copy()
print(newArr)


[[25 26 27 28 29]
 [45 46 47 48 49]
 [65 66 67 68 69]
 [85 86 87 88 89]]


## Numpy的统计分析

In [7]:
np.random.seed(60)
arr=np.random.randint(1,20,size=10)
print("创建的随机数：",arr)
arr.sort()
print("排序之后的数据",arr)

创建的随机数： [14  2  7 11 16  4  9 18  3  2]
排序之后的数据 [ 2  2  3  4  7  9 11 14 16 18]


In [8]:
np.random.seed(60)
arr=np.random.randint(1,20,size=10)
print("创建的随机数：",arr)
arr.sort()
print("排序之后的数据",arr)

创建的随机数： [14  2  7 11 16  4  9 18  3  2]
排序之后的数据 [ 2  2  3  4  7  9 11 14 16 18]


In [10]:
np.random.seed(40)
arr=np.random.randint(1,20,size=(5,5))
print("创建的随机数组\n",arr)
arr.sort(axis=0)
print("--------------------")
print(arr)
arr.sort(axis=1)
print("----------------------")
print(arr)

创建的随机数组
 [[ 7  8  6 19  2]
 [13  8 19 11 10]
 [ 1 18 10  9 16]
 [15  9 11  4  4]
 [ 8 18 14  6 19]]
--------------------
[[ 1  8  6  4  2]
 [ 7  8 10  6  4]
 [ 8  9 11  9 10]
 [13 18 14 11 16]
 [15 18 19 19 19]]
----------------------
[[ 1  2  4  6  8]
 [ 4  6  7  8 10]
 [ 8  9  9 10 11]
 [11 13 14 16 18]
 [15 18 19 19 19]]


## 间接排序 argsort（）
间接排序是

In [49]:
arr=np.array([0,6,3,9,1,7,0])
arr.sort()
print("元数据\n",arr)
print("索引排序后\n",arr.argsort())

元数据
 [0 0 1 3 6 7 9]
索引排序后
 [0 1 2 3 4 5 6]


## 间接排序 lexsort（）

In [27]:
a_totle=np.array([1,5,1,4,3,4,4])
ac =a_totle.copy()
print("总成绩的排序",ac)
print("总成绩排序索引",ac.argsort())
b_math=np.array([9,4,0,4,0,2,1])
bc=b_math.copy()
print("排序结果是",np.lexsort((bc,ac)))
print("----------------")
a_totle=np.array([1,5,1,4,3,4,4])
b_math=np.array([9,4,0,4,1,2,7])
print("排序结果是",np.lexsort((b_math,a_totle)))

总成绩的排序 [1 5 1 4 3 4 4]
总成绩排序索引 [0 2 4 3 5 6 1]
排序结果是 [2 0 4 6 5 3 1]
----------------
排序结果是 [2 0 4 5 3 6 1]


## 数据清洗 nuique() 查找唯一值并返回已排序结果

In [29]:
arrs=['train','bus','car','ship','subway','ship','bicycel']
print("去重取唯一",np.unique(arrs))

去重取唯一 ['bicycel' 'bus' 'car' 'ship' 'subway' 'train']


In [33]:
arrs=[1,2,6,3,8,3,0,1,7,9,2,0,3,5,4,8,9,3,4]
print("去重数组",np.unique(arrs))

去重数组 [0 1 2 3 4 5 6 7 8 9]


## 数据的重复操作
 1.tile（）
 2.repeat（）

In [35]:
arr= np.arange(5)
print(arr)
print(np.tile(arr,4))

[0 1 2 3 4]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [37]:
np.random.seed(50)
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)
print("----------")
print(np.repeat(arr, 2, axis=1))#对横轴重复
print("----------")
print(np.repeat(arr, 2, axis=0))#对纵轴重复

[[1 1 2]
 [5 7 6]
 [7 7 6]]
----------
[[1 1 1 1 2 2]
 [5 5 7 7 6 6]
 [7 7 7 7 6 6]]
----------
[[1 1 2]
 [1 1 2]
 [5 7 6]
 [5 7 6]
 [7 7 6]
 [7 7 6]]


## 统计函数

In [39]:
arr =np.arange(20).reshape(4,5)
print("创建的数组\n",arr)
print("求和",np.sum(arr))
print("纵轴求和",np.sum(arr,axis=0))
print("横轴求和",np.sum(arr,axis=1))

创建的数组
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
求和 190
纵轴求和 [30 34 38 42 46]
横轴求和 [10 35 60 85]


## 平均值

In [42]:
arr =np.arange(20).reshape(4,5)
print("球均值", np.mean(arr))
print("球纵轴均值", np.mean(arr, axis=0))
print("球横轴均值", np.mean(arr, axis=1))

球均值 9.5
球纵轴均值 [ 7.5  8.5  9.5 10.5 11.5]
球横轴均值 [ 2.  7. 12. 17.]


## 最值

In [44]:
print(np.min(arr))#最小值
print(np.max(arr))#最大值

0
19


##
### 1先输出所有元数据的价格
### 2对数据进行直接排序并输出
### 3去掉重复数据
### 4计算所有价格的总和
### 5获取最低价格
### 6获取最高价格

In [45]:
txtb=np.loadtxt('D:\Desktop\price.csv',delimiter=',',dtype=float)#读取
print(txtb)#1先输出所有元数据的价格

[  54.4    54.5    62.4    72.6    62.4    38.7    54.5    62.4    54.5
   38.7    48.     38.7    30.    109.    144.71   26.6   158.     85.3
  237.    237.     64.3   164.38  237.     46.6    94.     20.     17.99
   46.5    50.2   300.     38.7    63.9   300.     39.99  300.     38.7
   62.4    54.     62.4    46.6    40.     54.4    54.     67.1    60.
   39.     29.4    53.04   29.99   46.6    47.4    29.99   26.39   70.9
   64.7    49.     46.6   219.6    41.06   38.7    30.6   734.     33.4
   54.5    36.    500.     56.3    31.29   30.     46.5   189.6   118.5
   47.6    70.3   349.    189.6    38.7   189.6   189.6   189.6    46.6
   29.3    49.8    39.2    27.6    47.4    70.3   150.1   101.1   150.1
   31.8   126.4   150.     52.2    71.1    61.6    35.     62.4    16.99
  109.     23.6   118.5   118.5    89.     86.9   209.5    38.7    59.2
   58.4    78.    109.     27.     63.2    46.6    62.4   101.1    54.5
   95.     36.8    47.4    63.     46.6    78.2    67.4    31.6

In [51]:
txtb=np.loadtxt('D:\Desktop\price.csv',delimiter=',',dtype=float)#读取
txtb.sort()
print(txtb)#2对数据进行直接排序并输出

[   3.81    3.81    3.81    3.81    3.81    3.81    3.81    3.81    3.81
    3.81    3.81    3.81    3.81    3.81    3.81    3.81    3.81    3.81
    3.81    5.      5.      5.      5.      5.      5.      5.      5.
    5.      5.      5.      5.      5.      5.      5.      5.      5.
    5.      5.      5.      5.      6.1     6.1     6.1     6.1     6.1
    7.62    7.62    7.62    7.62    8.      8.      8.      8.      8.
    8.      8.      8.     10.     10.     10.     10.     15.     16.99
   17.3    17.99   19.7    20.     23.3    23.6    25.9    26.39   26.6
   27.     27.     27.6    29.3    29.4    29.99   29.99   30.     30.
   30.     30.6    30.8    31.29   31.6    31.8    32.5    33.1    33.4
   34.6    35.     36.     36.     36.8    37.4    38.6    38.7    38.7
   38.7    38.7    38.7    38.7    38.7    38.7    38.7    38.7    38.7
   38.7    38.7    38.7    38.7    38.7    39.     39.2    39.2    39.8
   39.99   40.     40.1    40.9    41.06   41.2    43.5    43.5  

In [52]:
txtb=np.loadtxt('D:\Desktop\price.csv',delimiter=',',dtype=float)#读取
print("去重取唯一",np.unique(txtb))#3去掉重复数据

去重取唯一 [   3.81    5.      6.1     7.62    8.     10.     15.     16.99   17.3
   17.99   19.7    20.     23.3    23.6    25.9    26.39   26.6    27.
   27.6    29.3    29.4    29.99   30.     30.6    30.8    31.29   31.6
   31.8    32.5    33.1    33.4    34.6    35.     36.     36.8    37.4
   38.6    38.7    39.     39.2    39.8    39.99   40.     40.1    40.9
   41.06   41.2    43.5    45.     46.5    46.6    47.1    47.4    47.6
   48.     49.     49.8    50.2    50.4    51.     51.3    52.2    52.6
   53.04   53.7    54.     54.4    54.5    56.3    58.4    58.5    59.2
   59.3    60.     60.5    61.6    62.4    63.     63.2    63.9    64.3
   64.7    67.1    67.4    69.1    70.3    70.8    70.9    71.1    71.8
   72.6    72.7    75.     77.4    78.     78.2    79.     85.     85.3
   86.9    88.     89.     89.6    94.     94.8    95.     98.     98.7
  101.1   101.9   109.    109.8   118.5   126.4   132.7   144.71  150.
  150.1   155.9   158.    164.38  171.    178.    188.    18